# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "##[group]Beginning of a group"
    echo "##[warning]Warning message"
    echo "##[error]Error message"
    echo "##[section]Start of a section"
    echo "##[debug]Debug text"
    echo "##[command]Command-line being run"
    echo "##[endgroup]"
    echo
    echo
    echo "##vso[task.logIssue type=error;sourcepath=B:\config.dsc;linenumber=0;columnnumber=0;code=DX0287;]F:\src\BuildXL.Internal.mpysson\config.dsc(0,0): Unable to create file access allowlist entry"
    echo "##vso[task.logIssue type=error;sourcepath=B:\config.dsc;code=DX0287;]F:\src\BuildXL.Internal.mpysson\config.dsc(0,0): Unable to create file access allowlist entry"
  displayName: 'Run a multi-line script'