jobs:
- job: SetBuildNumber
  displayName: Set build number
  timeoutInMinutes: 180
  steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false

  - template: ../../common/get-rm.yml
  
  - task: BatchScript@1
    name: Branding_PrereleaseTag
    displayName: Set Version number based on build settings and semantic version in branding.dsc copy
    inputs:
      filename: $(BuildXL.RM.ScriptsFolder)\SetVersionNumberForRollingBuild.cmd
      modifyEnvironment: true