# Worker pipeline

trigger: none   # This pipeline is explicitly scheduled

variables:
  - group: "BuildXL Common variables"
  - group: "BuildXL Secrets"
  - name: Domino.DogfoodPackagePath
    value: $(Build.StagingDirectory)\$(Build.BuildId)\Dogfood
  - name: BuildXL.RepoDirectory
    value: $(Build.Repository.LocalPath)
  - name: BuildXL.LogsDirectory
    value: $(BuildXL.RepoDirectory)\Out\Logs
  - name: PatArgs
    value: -OneEsPat $(PAT-TseBuild-AzureDevOps-1esSharedAssets-Package-Read) -CbPat $(PAT-TseBuild-AzureDevOps-CloudBuild-Packaging-Read) -MsEngGitPat $(PAT-TseBuild-AzureDevOps-MsEng-ReadCode) -VstsPat $(PAT-TseBuild-AzureDevOps-mseng-buildcache)
  - name: BxlScriptArgs
    value: -UseAdoBuildRunner -SharedCacheMode ConsumeAndPublish -Use Dev -DevRoot $(Domino.DogfoodPackagePath)\release\win-x64
  - name: BuildXLArgs
    value: /q:ReleaseDotNet6 /server- /p:[Sdk.BuildXL]microsoftInternal=1 /p:BUILDXL_FINGERPRINT_SALT=* /p:BuildXLWorkerAttachTimeoutMin=5 /logOutput:FullOutputOnWarningOrError /p:RetryXunitTests=1 /processRetries:3 /traceinfo:valdation=ReleasePipelineDistribution /enableIncrementalFrontEnd- /p:xunitSemaphoreCount=12

parameters:
  - name: DropName
    type: string

pool:
  name: BuildXL-DevOpsAgents-PME
jobs:
- job: Distributed_Clean_Workers
  strategy:
    parallel: 2  # CODESYNC: this value must be kept in sync with /dynamicBuildWorkerSlot in the worker pipeline 
  displayName: Clean distributed build (workers)

  steps:
  - task: ms-vscs-artifact.build-tasks.artifactDropDownloadTask-1.artifactDropDownloadTask@1
    displayName: 'Download ${{ parameters.DropName }} from drop'
    inputs:
      dropServiceURI: 'https://mseng.artifacts.visualstudio.com/DefaultCollection'
      buildNumber: '${{ parameters.DropName }}'
      destinationPath: '$(Domino.DogfoodPackagePath)'
      rootPaths: 'release/win-x64'

  - checkout: self
    fetchDepth: 1

  - template: ../common/set-artifacts-pat.yml
    parameters:
      AzDevPAT: $(PAT-TseBuild-AzureDevOps-MsEng)
  
  - template: ../common/journaling.yml
  
  - template: ../common/set-msvc-version.yml
  
  - script: |
      netsh advfirewall firewall add rule name="Open BuildXL inbound port" dir=in action=allow protocol=TCP localport=6979
      netsh advfirewall firewall add rule name="Open BuildXL outbound port" protocol=TCP localport=6979 action=allow dir=OUT
    displayName: Disable local firewall
  
  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: 'RunBxlWithPAT.ps1'
      arguments: '$(PatArgs) $(BxlScriptArgs) $(BuildXLArgs) /logsDirectory:$(BuildXL.LogsDirectory) /ado'
      workingDirectory: $(BuildXL.RepoDirectory)
    displayName: 'Run clean selfhost build distributed'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      AdoBuildRunnerWorkerPipelineRole: Worker  # TODO: This will be removed after we fully transition to the worker-pipeline model
  
  - task: PublishPipelineArtifact@1
    displayName: 'Upload logs'
    inputs:
      targetPath: $(BuildXL.LogsDirectory)
    condition: always()