parameters:
- name: Role
  type: string
  default: Orchestrator
  values:
  - Orchestrator
  - Worker

jobs:
- job: TestDistributed
  displayName: Test distributed build

  pool:
    name: BuildXL-DevOpsAgents-Linux-Stateless-PME
    os: linux

  variables:
    - name: BootstrapLocation
      value: $(System.DefaultWorkingDirectory)/Bootstrap

  templateContext:
    inputs:
    - input: checkout
      repository: self
      fetchDepth: 1
    - input: pipelineArtifact
      artifactName: 'Dev'
      targetPath: '$(BootstrapLocation)'
    sdl:
      credscan:
        enabled: false
      antimalwareScan:
        enabled: false
      publishLogs:
        enabled: false

  timeoutInMinutes: 20

  steps:
  - bash: |
      sudo mkdir /home/subst
      sudo mount --verbose --bind $(Build.SourcesDirectory) /home/subst
    displayName: Bind /home/subst to sources directory  

  # Run build
  - bash: |
      set -eu
      chmod +x $(BootstrapLocation)/AdoBuildRunner
      chmod +x $(BootstrapLocation)/bxl

      $(BootstrapLocation)/AdoBuildRunner \
        /cacheConfigLogGeneratedConfiguration \
        /cacheConfigStorageAccountEndpoint:https://l3bxlselfhost.blob.core.windows.net \
        /cacheConfigManagedIdentityId:eb694749-b1d6-45bc-b7af-2bd81603968a \
        /cacheConfigCacheType:EphemeralDatacenterWide \
        -- \
        /c:config.dsc /logsDirectory:$(Build.SourcesDirectory)/Out/Logs /p:BUILDXL_FINGERPRINT_SALT=* /p:BUILDXL_GRAPH_FINGERPRINT_SALT=* /replicateOutputsToWorkers+ /p:BuildXLMinimumWaitForRemoteWorkerMin=5 /dynamicBuildWorkerSlots:1
    displayName: Test distributed
    workingDirectory: /home/subst/Private/AdoDistributionTests
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      AdoBuildRunnerInvocationKey: LinuxDistributedValidation
      AdoBuildRunnerWorkerPipelineRole: ${{ parameters.Role }}
      TRANSFORMERS_SDK_DIR: /home/subst/Public/Sdk/Public/Transformers
      OUTPUT_DIR: /home/subst/Out

  - bash: sudo umount -v --lazy /home/subst
    condition: always()
    displayName: Unmount /home/subst
