trigger: none  # Explicitly scheduled for PRs

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: BuildSelfhost
  type: boolean
  default: true
- name: BxlCommonArgs
  type: string
  # We pass xunit semaphore `/p:[Sdk.BuildXL]xunitSemaphoreCount=8` to limit the number of parallel xunit pips.
  # Too many xunit pips running in parallel can cause the long running ones to hang. 
  default: --shared-comp /ado /cacheMiss:"[Bxl.Selfhost.Linux]" /logObservedFileAccesses /logoutput:FullOutputOnError /logsToRetain:10 /p:[Sdk.BuildXL]xunitSemaphoreCount=8
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: BuildXL-DevOpsAgents-Linux-Stateless-PME
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows

    stages:
    - stage: Bootstrap_Internal
      displayName: Bootstrap engine for validations
      dependsOn: []
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-bootstrap.yml@self
        parameters:
          BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
    
    - stage: Build_Public
      displayName: Public validation
      dependsOn: Bootstrap_Internal
      jobs:
        - template: /.azdo/linux/job-selfhost.yml@self
          parameters:
            BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
            ValidationName: PublicRelease
            BxlExtraArgs: /q:ReleaseLinux /forceAddExecutionPermission-

    - stage: Build_Internal
      displayName: Internal validation
      dependsOn: Bootstrap_Internal
      jobs:
      - template: /.azdo/linux/job-selfhost.yml@self
        parameters:
          BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
          ValidationName: InternalRelease
          BxlExtraArgs: --internal /q:ReleaseLinux /forceAddExecutionPermission-
          Role: Orchestrator
    
    - stage: Build_Internal_Workers
      displayName: Internal validation [Workers]
      dependsOn: Bootstrap_Internal
      jobs:
      - template: /.azdo/linux/job-selfhost.yml@self
        parameters:
          BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
          ValidationName: InternalRelease
          BxlExtraArgs: --internal /q:ReleaseLinux /forceAddExecutionPermission-
          Role: Worker

    - stage: Verify_PTrace
      displayName: PTrace validation
      dependsOn: Bootstrap_Internal  
      jobs:
      - template: /.azdo/linux/job-ptrace.yml@self
        parameters:
          BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
    
    - stage: Build_Distributed
      displayName: Distributed test [Orchestrator]
      dependsOn: [Build_Public, Build_Internal, Verify_PTrace] 
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-distributed.yml@self
        parameters:
          Role: Orchestrator
    
    - stage: Build_Distributed_Workers
      displayName: Distributed test [Workers]
      dependsOn: [Build_Public, Build_Internal, Verify_PTrace]
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-distributed.yml@self
        parameters:
          Role: Worker
