trigger:
  batch: true
  branches:
    include:
    - master

parameters:
- name: BuildSelfhost
  type: boolean
  default: true
- name: BuildLinuxRuntime
  type: boolean
  default: true
- name: PublishLinuxRuntimeNuget
  type: boolean
  default: false
- name: LinuxRuntimePackageVersion
  type: string
  default: 0.1.0-$(Build.BuildNumber)

jobs:
- ${{ if parameters.BuildSelfhost }}:
  - template: job-selfhost.yml
- ${{ if parameters.BuildLinuxRuntime }}:
  - template: job-linux-runtime.yml
    parameters:
      PublishNuget: ${{ parameters.PublishLinuxRuntimeNuget }}
      PackageVersion: ${{ parameters.LinuxRuntimePackageVersion }}