trigger: none  # Explicitly scheduled for PRs

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: BuildSelfhost
  type: boolean
  default: true

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: BuildXL-DevOpsAgents-Linux-Stateless-PME
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows

    stages:
    - stage: Build_Public
      displayName: Build (public)
      jobs:
      # Build and test selfhost with BuildXL
        - template: /.azdo/linux/job-selfhost.yml@self
          parameters:
            ValidationName: PublicRelease
            BxlExtraArgs: /q:ReleaseLinux /forceAddExecutionPermission-

    - stage: Build_Internal
      displayName: Build (internal) 
      dependsOn: []     # Run in parallel
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-selfhost.yml@self
        parameters:
          Distributed: true
          ValidationName: InternalRelease
          BxlExtraArgs: --internal /q:ReleaseLinux /forceAddExecutionPermission-

    - stage: Verify_PTrace
      displayName: PTrace validation
      dependsOn: []   # Run in parallel   
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-ptrace.yml@self
