steps:
- bash: |
    set -eu

    function addNugetSource {
      local source="$1"
      local name="$2"
      local password="$3"

      dotnet nuget remove source "$name" 2>&1 > /dev/null || true
      echo "Adding '$name' -> '$source'"
      dotnet nuget add source "$source" --name "$name" --username tsebuild --password "$password" --store-password-in-clear-text
    }

    addNugetSource "$(Feed-BuildXL.Selfhost)" "BuildXL.Selfhost" "$(PAT-TseBuild-AzureDevOps-CloudBuild)"
    addNugetSource "$(Feed-BuildXL)" "BuildXL" "$(PAT-TseBuild-AzureDevOps-1esSharedAssets)"
  displayName: Add NuGet Sources